esphome:
  name: temp-hum-sense1
  friendly_name: FOH Weather Sensor
  project:
    name: "Alex_Weisman.Climate_Sensor:_bme280"
    version: "2.0"

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "db43459a2ec3c546ee89483be38f8d13"
  platform: "esphome"

wifi:
  ssid: icewolffoh
  password: !secret wifi_password
  fast_connect: True
#  domain: .home.lan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temp-Hum-Sense1 Fallback Hotspot"
    password: "dG9zCnJvwvHv"

captive_portal:

# I2C configuration entry for ESP32
i2c:
  sda: 4
  scl: 5
  scan: true

#BME280 Configuration
sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
      filters:
        - offset: -4.0
    pressure:
      name: "BME280 Pressure"
      filters:
        - lambda: return x*0.030;
      unit_of_measurement: "inHg"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 60s

#Monitor WiFi Signal Strength
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

#Software Reboot Switch
switch:
  - platform: restart
    name: "FOH Sensor Restart"
