esphome:
  name: office-environmental
  friendly_name: Alex's Office Environmental
  project:
    name: "Alex_Weisman.Environmental_Sensor:_ccs811_&_bme280"
    version: "2.0"

esp8266:
  board: esp12e

# Enable logging
logger: 

# Enable Home Assistant API
api:
  encryption:
    key: "6I93BqVMqD5MtMom2wXJJrdQ/4X47WNPZ0sHGG8gNRc="
  reboot_timeout: 30min  

ota:
  password: "4a9eac574b98a2f193fab76a15ba8d2c"
  platform: "esphome"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  domain: !secret home_lan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office-Environmental"
    password: "wsudrmCLz2ej"

captive_portal:

# I2C configuration entry for ESP32
i2c:
  sda: 4
  scl: 5
  scan: true

#Sensor Setup
globals:
  - id: iaq_index
    type: int
    restore_value: no
    initial_value: '0'

sensor:
  #CCS811 @ 0x5B
  - platform: ccs811
    eco2:
      name: "Office eCO2 Value"
      id: eco2
    tvoc:
      name: "Office tVOC Value"
      id: tvoc
    version:
      name: "CCS811 Firmware Version"
      id: fwid
      entity_category: "diagnostic"
    baseline: 0x3481 #Baseline reading after 30mins uptime
    address: 0x5B
    update_interval: 60s  
    temperature: temp
    humidity: humi
  #BME280 @ 0x77
  - platform: bme280_i2c
    temperature:
      name: "Office Temperature"
      id: temp
      oversampling: 16x
      filters:
        - offset: 0.0
    pressure:
      name: "Office Pressure"
      id: press
      filters:
        - lambda: return x*0.030;
      unit_of_measurement: "inHg"
    humidity:
      name: "Office Humidity"
      id: humi
    address: 0x77    

#Monitor WiFi Signal Strength
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

#Monitor Uptime of ESP
  - platform: uptime
    name: Uptime Sensor
    entity_category: "diagnostic"        

#Setup Text based IAQ Readout
text_sensor:  
  - platform: template
    name: "Office IAQ"
    icon: "mdi:air-filter"
    lambda: |-
      id(iaq_index) = 0;
      
      #/*
      # * Transform indoor humidity values to IAQ points according to Indoor Air Quality UK: 
      # * http://www.iaquk.org.uk/
      # */
      if (id(humi).state < 10 or id(humi).state > 90) {
        id(iaq_index) += 1;
      }
      else if (id(humi).state < 20 or id(humi).state > 80) {
        id(iaq_index) += 2;
      }
      else if (id(humi).state < 30 or id(humi).state > 70) {
        id(iaq_index) += 3;
      }
      else if (id(humi).state < 40 or id(humi).state > 60) {
        id(iaq_index) += 4;
      }
      else if (id(humi).state >= 40 and id(humi).state <= 60) {
        id(iaq_index) += 5;
      }
      
      #/*
      # * Transform eCO2 values to IAQ points according to Indoor Air Quality UK: 
      # * http://www.iaquk.org.uk/
      # */
      if (id(eco2).state <= 600) {
        id(iaq_index) += 5;
      }
      else if (id(eco2).state <= 800) {
        id(iaq_index) += 4;
      }
      else if (id(eco2).state <= 1500) {
        id(iaq_index) += 3;
      }
      else if (id(eco2).state <= 1800) {
        id(iaq_index) += 2;
      }
      else if (id(eco2).state > 1800) {
        id(iaq_index) += 1;
      }
      
      #/*
      # * Transform TVOC values to IAQ points according to German environmental guidelines: 
      # * https://www.repcomsrl.com/wp-content/uploads/2017/06/Environmental_Sensing_VOC_Product_Brochure_EN.pdf
      # */
      if (id(tvoc).state <= 65) {
        id(iaq_index) += 5;
      }
      else if (id(tvoc).state <= 220) {
        id(iaq_index) += 4;
      }
      else if (id(tvoc).state <= 660) {
        id(iaq_index) += 3;
      }
      else if (id(tvoc).state <= 2200) {
        id(iaq_index) += 2;
      }
      else if (id(tvoc).state > 2200) {
        id(iaq_index) += 1;
      }

      #/*
      # * Transform IAQ index to human readable text according to Indoor Air Quality UK: 
      # * http://www.iaquk.org.uk/
      # */
      ESP_LOGD("main", "Current IAQ index %d", id(iaq_index));
      
      if (id(iaq_index) <= 6) {
        return {"Unhealty"};
      }
      else if (id(iaq_index) <= 9) {
        return {"Poor"};
      }
      else if (id(iaq_index) <= 12) {
        return {"Moderate"};
      }
      else if (id(iaq_index) <= 14) {
        return {"Good"};
      }
      else if (id(iaq_index) > 14) {
        return {"Excellent"};
      }
      
      return {};
    update_interval: 60s    

#Software Reboot Switch
switch:
  - platform: restart
    name: "Office IAQ Sensor Restart"    