esphome:
  name: "brine-monitor"
  friendly_name: brine_monitor

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XzEAlpHy1RSaoD0igjOJl8gzgdeqZ6rJfrso0opw5bo="

ota:
  password: "0981b73a2728e582305b97b567dc9688"
  platform: "esphome"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Brine-Monitor Fallback Hotspot"
    password: "HH9URkZ28QOb"

captive_portal:



# Oil Level Sensor
sensor:
  - platform: ultrasonic
    trigger_pin: 5
    echo_pin: 4
    name: "Brine Tank Salt Level"
    unit_of_measurement: "gal"
    update_interval: 60s
    filters:
    - sliding_window_moving_average:
        window_size: 6
        send_every: 6
        send_first_at: 1

#Monitor WiFi Signal Strength
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

#Monitor Uptime of ESP
  - platform: uptime
    name: Uptime Sensor
    entity_category: "diagnostic"

#Software Reboot Switch
switch:
  - platform: restart
    name: "Oil Level Sensor Restart" 