esphome:
  name: laser-controller
  project:
    name: "Alex_Weisman.K40_Laser_Controller"
    version: "1.1"
  includes:
    - my_sensor.h

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5QDRhjPaS5XGo2ByiGZGoe0/tCwYevqg5LcpnZi/80I="

ota:
  password: "19a7f87839a4e7db3045e9cc4ecc1c81"
  platform: "esphome"

wifi:
  ssid: !secret g_wifi_ssid
  password: !secret wifi_password
#  domain: !secret home_lan
  fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Laser-Controller"
    password: "nUAx7E04nSzA"

captive_portal:

# I2C configuration entry for ESP32
i2c:
  sda: 4
  scl: 5
  scan: true

# PCF8575 GPIO Expander Configuration
pcf8574:
  - id: "gpio_hub_1"
    address: 0x20
    pcf8575: True

# SPI interface configuration
spi:
  miso_pin: 12
  clk_pin: 14

#----SENSORS----
sensor:
  # MAX6675 Thermocouple Interface
  - platform: max6675
    name: "Laser Coolant Temperature"
    cs_pin: 15
    update_interval: 60s

  # Coolant Flow Sensor
  - platform: pulse_meter
    pin:
      number: 3
      mode: input_pullup
    unit_of_measurement: "L/Min"
    name: "Coolant Flow Rate"
    icon: "mdi:hydro-power"
    accuracy_decimals: 3
    filters:
      - lambda: return (x/(98*60)); # f=(98*Q)  Q=L/min
      - throttle_average: 10s
      - heartbeat: 5s
      #- multiply: 0.0102
  
  #---Diagnostic Sensors---
  # Monitor WiFi Signal Strength
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
  # Monitor Uptime of ESP
  - platform: uptime
    name: "Uptime"
    entity_category: "diagnostic"

#----SWITCHES----
switch:
  #GPIO Hub Outputs
  - platform: gpio
    name: "Relay 1"
    pin:
      pcf8574: gpio_hub_1
      number: 0
      mode:
        output: True
      inverted: true
  - platform: gpio
    name: "Relay 2"
    pin:
      pcf8574: gpio_hub_1
      number: 1
      mode:
        output: True
      inverted: True
  - platform: gpio
    name: "Relay 3"
    pin:
      pcf8574: gpio_hub_1
      number: 2
      mode:
        output: True
      inverted: True
  - platform: gpio
    name: "Relay 4"
    pin:
      pcf8574: gpio_hub_1
      number: 3
      mode:
        output: True
      inverted: True

  #Software Reboot Switch
  - platform: restart
    name: "Laser Controller Restart"