esphome:
  name: oil-level-sensor
  friendly_name: Heating Oil Level Sensor
  project:
    name: "Alex Weisman.Oil Level Sensor"
    version: "1.0"  

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 30min  

ota:
  password: "ce2e2fc210bbaaf689f76ba9ce32a244"
  platform: "esphome"

wifi:
  ssid: !secret 24wifi_ssid
  password: !secret wifi_password
#  domain: !secret home_lan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Oil-Level-Sensor"
    password: "ZeRudxBJIVdH"

captive_portal:

# Oil Level Sensor
sensor:
  - platform: ultrasonic
    trigger_pin: 5
    echo_pin: 4
    name: "Oil Level Sensor"
    unit_of_measurement: "gal"
    update_interval: 10s
    filters:
    - calibrate_polynomial:
       degree: 6
       datapoints:
        # Map 0.0 (from sensor) to 0.0 (true value)
        - 0.0381 -> 275.00
        - 0.0631 -> 271.00
        - 0.0881 -> 268.00
        - 0.1143 -> 265.00
        - 0.1391 -> 261.00
        - 0.1651 -> 256.00
        - 0.1901 -> 250.00
        - 0.2151 -> 244.00
        - 0.2411 -> 238.00
        - 0.2661 -> 231.00
        - 0.2921 -> 224.00
        - 0.2551 -> 217.00
        - 0.3421 -> 210.00
        - 0.3681 -> 203.00
        - 0.3931 -> 195.00
        - 0.4191 -> 187.00
        - 0.4441 -> 180.00
        - 0.4691 -> 172.00
        - 0.4951 -> 165.00
        - 0.5201 -> 157.00
        - 0.5461 -> 150.00
        - 0.5711 -> 142.00
        - 0.5961 -> 135.00
        - 0.6221 -> 127.00
        - 0.6471 -> 120.00
        - 0.6731 -> 112.00
        - 0.6981 -> 105.00
        - 0.7231 -> 97.00
        - 0.7491 -> 90.00
        - 0.7741 -> 82.00
        - 0.8001 -> 75.00
        - 0.8251 -> 67.00
        - 0.8501 -> 60.00
        - 0.8761 -> 53.00
        - 0.9011 -> 46.00
        - 0.9271 -> 39.00
        - 0.9521 -> 32.00
        - 0.9771 -> 26.00
        - 1.0031 -> 20.00
        - 1.0281 -> 14.00
        - 1.0541 -> 9.00
        - 1.0791 -> 5.00
        - 1.1041 -> 2.00
        - 1.1301 -> 0.00
    - sliding_window_moving_average:
        window_size: 6
        send_every: 6
        send_first_at: 1

#Monitor WiFi Signal Strength
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

#Monitor Uptime of ESP
  - platform: uptime
    name: Uptime Sensor
    entity_category: "diagnostic"

#Software Reboot Switch
switch:
  - platform: restart
    name: "Oil Level Sensor Restart" 