esphome:
  name: icewolf3d-controller
  project:
    name: "Alex_Weisman.3DPrinter&Enclosure_Monitor&Controller"
    version: "2.0"

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "E65Ku8alo2SVozCL/FJxlRjd/j+IFXDX3I3vzCZg0gw="

ota:
  password: "a6c86419b64945de944a81a29c39fd08"
  platform: "esphome"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  domain: !secret home_lan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Icewolf3D-Controller"
    password: "PFn2SzZyvedr"

captive_portal:

# I2C configuration entry for ESP32
i2c:
  sda: 4
  scl: 5
  scan: true

#----SENSONRS----
#BME280 Configuration
sensor:
  - platform: bme280_i2c
    temperature:
      name: "IceWolf3D Enclosure Temperature"
      id: temp
      oversampling: 16x
      filters:
        - offset: 0.0
    pressure:
      name: "IceWolf3D Enclosure Pressure"
      id: press
      filters:
        - lambda: return x*0.030;
      unit_of_measurement: "inHg"
    humidity:
      name: "IceWolf3D Enclosure Humidity"
      id: hum
    address: 0x76
    #update_interval: 60s

#Monitor WiFi Signal Strength
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

#Monitor Uptime of ESP
  - platform: uptime
    name: "Uptime"
    entity_category: "diagnostic"

#----SWITCHES----
#Output control for relays
switch:
  - platform: gpio
    pin:
      number: 15
    name: "Enclosure Lights"
    icon: "mdi:wall-sconce-round"
  - platform: gpio
    pin:
      number: 13
    name: "Printer Lights"
    icon: "mdi:led-strip"
  - platform: gpio
    pin:
      number: 12
    name: "Relay 3"
  - platform: gpio
    pin:
      number: 14
    name: "Printer Power"
    icon: "mdi:printer-3d"
#Software Reboot Switch
  - platform: restart
    name: "3D Printer Controller Restart"